ALTER TABLE `user` DROP `origen`;

ALTER TABLE `user` DROP `pertenece_a`;

ALTER TABLE `user` DROP `is_vendendor`;

drop view view_user;
CREATE VIEW `view_user`  AS SELECT `user`.`id` AS `id`, `user`.`username` AS `username`, `user`.`email` AS `email`, `user`.`titulo_personal_id` AS `titulo_personal_id`, `titulo_personal`.`singular` AS `titulo_personal`, `user`.`nombre` AS `nombre`, `user`.`apellidos` AS `apellidos`, concat_ws(' ',`user`.`nombre`,`user`.`apellidos`) AS `nombre_completo`, `auth_assignment`.`item_name` AS `perfil`, `user`.`sexo` AS `sexo`, `user`.`fecha_nac` AS `fecha_nac`, `user`.`telefono` AS `telefono`, `user`.`telefono_movil` AS `telefono_movil`, `user`.`cargo` AS `cargo`, `user`.`departamento_id` AS `departamento_id`, `departamento`.`singular` AS `departamento`, `esys_direccion`.`id` AS `direccion_id`, `esys_direccion`.`direccion` AS `direccion`, `esys_direccion`.`num_ext` AS `num_ext`, `esys_direccion`.`num_int` AS `num_int`, `esys_direccion`.`referencia` AS `referencia`, `esys_direccion`.`estado_id` AS `estado_id`, `estado`.`singular` AS `estado`, `esys_direccion`.`municipio_id` AS `municipio_id`, `municipio`.`singular` AS `municipio`, `user`.`comentarios` AS `comentarios`, `user`.`informacion` AS `informacion`, `user`.`status` AS `status`, `user`.`created_at` AS `created_at`, `user`.`created_by` AS `created_by`, concat_ws(' ',`created`.`nombre`,`created`.`apellidos`) AS `created_by_user`, `user`.`updated_at` AS `updated_at`, `user`.`updated_by` AS `updated_by`, concat_ws(' ',`updated`.`nombre`,`updated`.`apellidos`) AS `updated_by_user` FROM ((((((((`user` left join `esys_lista_desplegable` `titulo_personal` on((`user`.`titulo_personal_id` = `titulo_personal`.`id`))) left join `esys_lista_desplegable` `departamento` on((`user`.`departamento_id` = `departamento`.`id`))) left join `auth_assignment` on((`user`.`id` = `auth_assignment`.`user_id`))) left join `esys_direccion` on(((`user`.`id` = `esys_direccion`.`cuenta_id`) and (`esys_direccion`.`cuenta` = 1) and (`esys_direccion`.`tipo` = 1)))) left join `esys_lista_desplegable` `estado` on(((`esys_direccion`.`estado_id` = `estado`.`id_2`) and (`estado`.`label` = 'crm_estado')))) left join `esys_lista_desplegable` `municipio` on(((`esys_direccion`.`municipio_id` = `municipio`.`id_2`) and (`esys_direccion`.`estado_id` = `municipio`.`param1`) and (`municipio`.`label` = 'crm_municipio')))) left join `user` `created` on((`user`.`created_by` = `created`.`id`))) left join `user` `updated` on((`user`.`updated_by` = `updated`.`id`))) ;

